name: Zip Resource Pack
on:
  push:
    branches:
      - master
    paths-ignore:
      - Runecraft_Resourcepack.zip

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Zip the target folder
        run: |
          zip -r Runecraft_Resourcepack.zip runecraftResourcePack/
          

      - name: Commit and push ZIP file
        run: |
          git add Runecraft_Resourcepack.zip
          git commit -m "Add zipped folder"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
